#$ -cwd
#$ -q sandbox
#$ -pe mpi 4
#$ -S /bin/bash

# Modules used
module load blast/v2.8.1

#run blast vs NCBI nucleotide db
#Create correct output file name
GENE=$(pwd | cut -d '/' -f 7)
FILEIN="${GENE}_all_seq.fa"
FILEOUT="${GENE}_BLAST_out.txt"
blastn -db /db/latest_ncbi/nt -query $FILEIN -task dc-megablast -outfmt '6 qseqid sseqid slen pident length mismatch bitscore' -num_threads 4 > $FILEOUT
