#This script matches prediction transcripts generated by prokka, to 12 preselected chloroplast genomes obtained from genbank 
# Modules used
module load blast/v2.8.1

mkdir -p known_genome_match
SUBJECTSTEM=$( pwd |cut -d '/' -f 7)
echo $SUBJECTSTEM
FILE="known_genome_match/${SUBJECTSTEM}_best_genome_match.txt"
if [ -f "$FILE" ] ; then
    rm "$FILE"
fi
for GENOME in `find ../reference_genomes/*_coding_seque*ce.fa -maxdepth 0 -type f`; do
     SUBJECTSTEM=$( pwd |cut -d '/' -f 7)
     FILESTEM=$(echo $GENOME |cut -d '/' -f 3|cut -d '.' -f 1)
     alignment_sum=$(blastn -db $GENOME -query *[0-9].ffn -task dc-megablast -outfmt '6 qseqid sseqid slen pident length mismatch bitscore' -num_threads 4 | sort -uk1,1 | cut -f5 | paste -sd+ - | bc)
     echo $(echo $FILESTEM	) $alignment_sum >> "$FILE"
done
